import Link from "next/link";
import "./globals.css";
import { Controls } from "./Controls";

export const metadata = {
  title: "WEB Tutorial",
  description: "Generated by YSE",
};

export default async function RootLayout({ children }) {
  const res = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/topics`, {cache: 'no-store'});
  const topics = await res.json();
  return (
    <html lang="en">
      <body>
        <h1><Link href="/">WEB</Link></h1>

        <ol>
          {topics.map(topic => {
            return <li key={topic.id}><Link href={`/read/${topic.id}`}>{topic.title}</Link></li>
          })}
        </ol>

        <p>=== children ===</p>
        {children}
        <p>=== children ===</p>

        <Controls />
      </body>
    </html>
  );
}
